#!/usr/bin/env npx tsx
/**
 * Auto-generates architecture-diagram.md from actual file references.
 * Like a database VIEW — always reflects the real state.
 *
 * Usage: npx tsx scripts/generate-knowledge-diagram.ts
 */

import { readdirSync, readFileSync, statSync, existsSync, writeFileSync } from 'fs';
import { resolve, join, relative } from 'path';

const ROOT = resolve(__dirname, '..');
const KNOWLEDGE_DIR = resolve(ROOT, '.knowledge');
const OUTPUT = resolve(KNOWLEDGE_DIR, 'architecture-diagram.md');

interface FolderRef {
  folder: string;
  targets: string[];
}

function collectFolderRefs(): FolderRef[] {
  const refs: FolderRef[] = [];
  function walk(dir: string) {
    const claudeMd = join(dir, 'CLAUDE.md');
    if (existsSync(claudeMd)) {
      const content = readFileSync(claudeMd, 'utf-8');
      const targets = content
        .split('\n')
        .filter(l => l.startsWith('See:'))
        .map(l => l.replace('See: .knowledge/', '').trim());
      if (targets.length > 0) {
        refs.push({ folder: relative(ROOT, dir), targets });
      }
    }
    for (const entry of readdirSync(dir)) {
      if (['node_modules', '.git', 'build', 'dist'].includes(entry)) continue;
      const full = join(dir, entry);
      if (statSync(full).isDirectory()) walk(full);
    }
  }
  // CUSTOMIZE: add your source directories
  for (const dir of ['src', 'e2e', '__tests__', 'maestro']) {
    const d = resolve(ROOT, dir);
    if (existsSync(d)) walk(d);
  }
  return refs;
}

function collectKnowledgeFiles(): string[] {
  const files: string[] = [];
  const skip = new Set(['README.md', 'gaps.md', 'ENGINE-TYPES.md', 'architecture-diagram.md', 'index.md']);
  function walk(dir: string) {
    for (const entry of readdirSync(dir)) {
      const full = join(dir, entry);
      if (statSync(full).isDirectory()) walk(full);
      else if (entry.endsWith('.md') && !skip.has(entry)) files.push(relative(KNOWLEDGE_DIR, full));
    }
  }
  walk(KNOWLEDGE_DIR);
  return files.sort();
}

function collectCrossRefs(): { source: string; target: string }[] {
  const refs: { source: string; target: string }[] = [];
  for (const file of collectKnowledgeFiles()) {
    const content = readFileSync(join(KNOWLEDGE_DIR, file), 'utf-8');
    for (const match of content.matchAll(/\.knowledge\/([a-zA-Z0-9/_.-]+\.md)/g)) {
      if (match[1] !== file) refs.push({ source: file, target: match[1] });
    }
  }
  return refs;
}

function findOrphans(allFiles: string[], folderRefs: FolderRef[]): string[] {
  const referenced = new Set<string>();
  for (const ref of folderRefs) for (const t of ref.targets) referenced.add(t);
  return allFiles.filter(f => {
    if (f.startsWith('templates/') || f.startsWith('patterns/') || f.startsWith('rubrics/')) return false;
    return !referenced.has(f);
  });
}

function generate(): string {
  const folderRefs = collectFolderRefs();
  const allFiles = collectKnowledgeFiles();
  const crossRefs = collectCrossRefs();
  const orphans = findOrphans(allFiles, folderRefs);

  const lines: string[] = [
    '# Knowledge Graph — Entity Relationship Diagram',
    '',
    '> Auto-generated by `scripts/generate-knowledge-diagram.ts`. Do not edit manually.',
    '',
    '## Folder CLAUDE.md → Knowledge (Foreign Keys)',
    '',
    '```',
  ];

  for (const ref of folderRefs.sort((a, b) => a.folder.localeCompare(b.folder))) {
    lines.push(`${ref.folder.padEnd(28)} → ${ref.targets.map(t => t.replace('.md', '')).join(', ')}`);
  }
  lines.push('```', '');

  if (crossRefs.length > 0) {
    lines.push('## Cross-References', '', '```');
    for (const ref of crossRefs) {
      lines.push(`${ref.source.replace('.md', '').padEnd(40)} → ${ref.target.replace('.md', '')}`);
    }
    lines.push('```', '');
  }

  lines.push('## Orphaned Nodes', '');
  if (orphans.length === 0) {
    lines.push('None.');
  } else {
    for (const o of orphans) lines.push(`- \`${o}\``);
  }
  lines.push('');

  return lines.join('\n');
}

writeFileSync(OUTPUT, generate());
const refs = collectFolderRefs();
console.log(`Generated: ${relative(ROOT, OUTPUT)}`);
console.log(`  ${refs.length} folder CLAUDE.md files, ${collectKnowledgeFiles().length} knowledge files`);
